name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4 # Similar to above, check out your code to run

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      
    - name: Enable KVM  
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq --yes qemu-kvm libvirt-dev libvirt-clients
        sudo adduser $USER kvm
        sudo chown $USER /dev/kvm
        kvm-ok || true
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Install system images
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-29;google_apis;x86_64"
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-29"
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.2"

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install and Run Firebase
      run: npm install -g firebase-tools
    
    - name: Start Emulator
      run: firebase emulators:start --only firestore &
      env:
          FIRESTORE_EMULATOR_HOST: localhost:8080

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        profile: pixel_9
        script: ./gradlew connectedCheck
      env:
        FIRESTORE_EMULATOR_HOST: 10.0.2.2:8080

  
